### ISSUE TITLE
Cant open own cars anymore when i get out.

### ISSUE THREAD

**Issue by Cyboraa** [AxDSan/esx_nocarjack#3]
I installed this resource into my server but now if i get out of my own car it will also lock itself. Can somebody give me a solution for this problem.

**Comment by AxDSan** [comment]
Hey there,

Yes, It has come to my attention that there have been some issues going on with this resource, this issue specifically could be solved by fixing the logic for when the player is going to open a car, it would be best to check if the player is the current owner of the vehicle and then perform the other checks: https://github.com/AxDSan/esx_nocarjack/blob/master/client/nocarjack_cl.lua#L69

Sadly as I don't work on this anymore, your best shot would be to fork the project, and work on your own and see how it goes from there.

Another thing would be that someone could submit a PR solving the issue and I will gladly merge it along with the current active branch.
