### ISSUE TITLE
Found your problem

### ISSUE THREAD

**Issue by Dogasawi** [AxDSan/esx_nocarjack#5]
I have been trying to figure out issue with job cars and personal cars getting locked, finally figured it out.

on line 68 of the client lua:

				if (lock == 7 or pedd) then

unfortunately, LUA doesnt consider ZERO to be the same as FALSE. pedd is an int returned from a function that returns 0 instead of Nil if it doesnt find (in this case a Ped in the driver seat)

this means your above condition is ALWAYS TRUE (because pedd will always be 0 or some other number unless the function completely fails somehow)

so in order for this line to function as intended, you must change it to:

				if ((lock == 7) or (pedd ~= 0 )) then

that should fix basically every problem since vehicles spawned by scripts generally dont set the lock status to 7   (of course, anyone who is using a script where a car is spawned and lock status is set to 7 will get locked out, but i doubt anyone is doing that. they are generally setting locks to either 0 or 1 or 2.  7 is really only used by the game engines auto spawned vehicles)

**Comment by Dogasawi** [comment]
also consider moving this if statement (along with the local declaration of 'pedd',  up to the top after lock status is first checked, to prevent unnecessarily running code that doesnt need to be run.

**Comment by AxDSan** [comment]
Awesome, thanks for the input!
