### ISSUE TITLE
Locks Taxi cabs 

### ISSUE THREAD

**Issue by ControlTheNarrativ3** [AxDSan/esx_nocarjack#7]
is there any way to "whitelist" the taxi model so it will be open for everyone?

**Comment by AxDSan** [comment]
Yes, just grab the taxi vehicle model, and add it to: https://github.com/AxDSan/esx_nocarjack/blob/3b061706574f5efd79d4def7883ea7a5f746170f/cfg/nocarjack.lua#L24
