### ISSUE TITLE
Not working for Boats, only Seashark :(

### ISSUE THREAD

**Issue by hakkemanu** [AxDSan/esx_nocarjack#9]
Not working for Boats, only Seashark :(

**Comment by AxDSan** [comment]
It's been a long time since I don't maintain this anymore, you're out of luck... you can submit a PR if you work on something, or check other forks and see if people maintain them.

**Comment by hakkemanu** [comment]
You don’t have a tip ?

0x90 <notifications@github.com> schrieb am Fr. 29. Jan. 2021 um 20:59:
